name: Vue.js Brasil
description: Artigos em Português sobre Vue.js
meta_description: Artigos em Português sobre Vue.js

warning: true
warning_message: "Estamos em processo de migração. <br/> Algumas coisas podem não funcionar"

permalink: /:title
markdown: kramdown
highlighter: pygments
logo: true
paginate: 15
baseurl: 
domain_name: 'http://www.vuejs-brasil.com.br/'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

#authors
authors:
  danielschmitz:
    name: Daniel Schmitz
    gravatar: b2da8fcc6cfdaf3bbe1f17aa9fabde39
    web: http://danielschmitz.com.br
    description: Daniel Schmitz é autor de vários livros sobre programação e desenvolvimento de sistemas
    github: danielschmitz
  vedovelli:
    name: Fábio Vedovelli
    gravatar: 63070a46ae3ac45778a7c5fa9e73f4a5
    web: http://vedovelli.com.br
    description: 
    github: vedovelli
