# Site settings
title: Vue.js Brasil - Comunidade Brasileira de Vue.js
description: Artigos em Português sobre Vue.js
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://vuejs-br.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings (Não usado no blog)
username: Lorem Ipsum
user_description: Anon Developer at Lorem Ipsum Dolor
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
